/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author murtaza
 */
@SuppressWarnings("serial")
public class home extends javax.swing.JFrame {

  DefaultTableModel dm;
    Connection con =connection.getConnection();
    ResultSet rst=null;
    PreparedStatement pst=null;
    public home() {
        initComponents();
        jlbl.setVisible(false);
        table();
        
    }
    
    
private void check()
{
    if (jlbl.getText().equals("true"))
    {
        jsp.setVisible(true);
        jtable.setVisible(true);
        jusers.setVisible(true);
        jlbltype.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-crown-50.png")));
        jlbltype.setText("Admin");
        
    }
    else
    {
        jsp.setVisible(false);
        jtable.setVisible(false);
        jusers.setVisible(false);
        jlbltype.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/crown-4-48.png")));
        jlbltype.setText("User");
    }
        }


private void table()
{
    try  {
        String sql=("Select * from login");
        pst=con.prepareStatement(sql);
        rst=pst.executeQuery(sql);
        DefaultTableModel dm = (DefaultTableModel) jtable.getModel();
        ResultSetMetaData rsmd = rst.getMetaData();
        int columnCount = rsmd.getColumnCount();
        while (rst.next()) 
        {
            String[] a = new String[columnCount];
            for(int i = 0; i < columnCount; i++)
            {
                a[i] = rst.getString(i+1);
 
            }
            dm.addRow(a);
        }
        jtable.setDefaultEditor(Object.class, null);
        }
        catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
}

  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jsp = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jlbltype = new javax.swing.JLabel();
        jlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlblname = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jcustomer = new javax.swing.JMenu();
        jaddcustomer = new javax.swing.JMenuItem();
        jpurchase = new javax.swing.JMenu();
        jaddpurchase = new javax.swing.JMenuItem();
        jsales = new javax.swing.JMenu();
        jaddinvoice = new javax.swing.JMenuItem();
        jcompany = new javax.swing.JMenu();
        jaddcompany = new javax.swing.JMenuItem();
        jlist = new javax.swing.JMenu();
        jpurchaselist = new javax.swing.JMenuItem();
        jsaleslist = new javax.swing.JMenuItem();
        jcustomerlist = new javax.swing.JMenuItem();
        jcompanylist = new javax.swing.JMenuItem();
        jusers = new javax.swing.JMenu();
        jaddusers = new javax.swing.JMenuItem();
        jlogout = new javax.swing.JMenu();
        jclose = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(254, 254, 254));
        setForeground(java.awt.Color.white);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(18, 165, 245));

        jsp.setBackground(new java.awt.Color(0, 156, 255));

        jtable.setBackground(new java.awt.Color(254, 254, 254));
        jtable.setBorder(new javax.swing.border.MatteBorder(null));
        jtable.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jtable.setForeground(new java.awt.Color(1, 1, 1));
        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "User", "Security Question", "Security Answer", "Date Of Birth", "Is Admin", "Passwrod"
            }
        ));
        jtable.setGridColor(new java.awt.Color(254, 254, 254));
        jtable.setSelectionBackground(new java.awt.Color(0, 255, 114));
        jtable.setSelectionForeground(new java.awt.Color(254, 242, 242));
        jsp.setViewportView(jtable);

        jlbltype.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jlbltype.setForeground(new java.awt.Color(240, 255, 0));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 108));
        jLabel1.setText("Logged In As");

        jlblname.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jlblname.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 1364, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbl)
                        .addGap(372, 372, 372))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(jlbltype)
                        .addGap(50, 50, 50)
                        .addComponent(jlblname)
                        .addGap(120, 120, 120))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(370, Short.MAX_VALUE)
                .addComponent(jsp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jlbl)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblname)
                            .addComponent(jlbltype)
                            .addComponent(jLabel1))
                        .addContainerGap())))
        );

        jMenuBar1.setBackground(new java.awt.Color(185, 0, 255));
        jMenuBar1.setForeground(new java.awt.Color(185, 0, 255));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N

        jcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-customer-50.png"))); // NOI18N
        jcustomer.setText("Customers   ");
        jcustomer.setFocusable(false);
        jcustomer.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jcustomer.setNextFocusableComponent(jpurchase);

        jaddcustomer.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jaddcustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-add-35.png"))); // NOI18N
        jaddcustomer.setText("Add Customers             ");
        jaddcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddcustomerActionPerformed(evt);
            }
        });
        jcustomer.add(jaddcustomer);

        jMenuBar1.add(jcustomer);

        jpurchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-cash-register-50.png"))); // NOI18N
        jpurchase.setText("Purchase     ");
        jpurchase.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jpurchase.setNextFocusableComponent(jsales);

        jaddpurchase.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jaddpurchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-add-35.png"))); // NOI18N
        jaddpurchase.setText("Add New Products   ");
        jaddpurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddpurchaseActionPerformed(evt);
            }
        });
        jpurchase.add(jaddpurchase);

        jMenuBar1.add(jpurchase);

        jsales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-invoice-50.png"))); // NOI18N
        jsales.setText("Sales      ");
        jsales.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jsales.setNextFocusableComponent(jcompany);

        jaddinvoice.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jaddinvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-add-35.png"))); // NOI18N
        jaddinvoice.setText("Create Invoice");
        jaddinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddinvoiceActionPerformed(evt);
            }
        });
        jsales.add(jaddinvoice);

        jMenuBar1.add(jsales);

        jcompany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-new-company-50.png"))); // NOI18N
        jcompany.setText("Company     ");
        jcompany.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jcompany.setNextFocusableComponent(jlist);

        jaddcompany.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jaddcompany.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-add-35.png"))); // NOI18N
        jaddcompany.setText("Add New Companies ");
        jaddcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddcompanyActionPerformed(evt);
            }
        });
        jcompany.add(jaddcompany);

        jMenuBar1.add(jcompany);

        jlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-list-view-50.png"))); // NOI18N
        jlist.setText("List       ");
        jlist.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jlist.setNextFocusableComponent(jusers);

        jpurchaselist.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jpurchaselist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-menu-35.png"))); // NOI18N
        jpurchaselist.setText("Purchase List");
        jpurchaselist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpurchaselistActionPerformed(evt);
            }
        });
        jlist.add(jpurchaselist);

        jsaleslist.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jsaleslist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-menu-35.png"))); // NOI18N
        jsaleslist.setText("Sales List");
        jsaleslist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsaleslistActionPerformed(evt);
            }
        });
        jlist.add(jsaleslist);

        jcustomerlist.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jcustomerlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-menu-35.png"))); // NOI18N
        jcustomerlist.setText("Customer List");
        jcustomerlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcustomerlistActionPerformed(evt);
            }
        });
        jlist.add(jcustomerlist);

        jcompanylist.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jcompanylist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-menu-35.png"))); // NOI18N
        jcompanylist.setText("Comapny List");
        jcompanylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcompanylistActionPerformed(evt);
            }
        });
        jlist.add(jcompanylist);

        jMenuBar1.add(jlist);

        jusers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-user-group-50.png"))); // NOI18N
        jusers.setText("Users     ");
        jusers.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jusers.setNextFocusableComponent(jlogout);

        jaddusers.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jaddusers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-add-35.png"))); // NOI18N
        jaddusers.setText("Add New Users");
        jaddusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddusersActionPerformed(evt);
            }
        });
        jusers.add(jaddusers);

        jMenuBar1.add(jusers);

        jlogout.setForeground(new java.awt.Color(0, 0, 0));
        jlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-shutdown-50.png"))); // NOI18N
        jlogout.setText("Logout");
        jlogout.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jlogout.setNextFocusableComponent(jcustomer);
        jlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlogoutMouseClicked(evt);
            }
        });
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });
        jlogout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlogoutKeyPressed(evt);
            }
        });
        jMenuBar1.add(jlogout);

        jclose.setForeground(new java.awt.Color(0, 0, 0));
        jclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventory/icons/icons8-multiply-50.png"))); // NOI18N
        jclose.setText("Close");
        jclose.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcloseMouseClicked(evt);
            }
        });
        jclose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcloseKeyPressed(evt);
            }
        });
        jMenuBar1.add(jclose);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1370, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        check();
    }//GEN-LAST:event_formWindowOpened

    private void jaddcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddcustomerActionPerformed
        customers cs =new customers();
        cs.setVisible(true);
    }//GEN-LAST:event_jaddcustomerActionPerformed

    private void jaddcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddcompanyActionPerformed
        company comp =new company();
        comp.setVisible(true);
    }//GEN-LAST:event_jaddcompanyActionPerformed

    private void jaddpurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddpurchaseActionPerformed
        purchase prchse =new purchase();
        prchse.setVisible(true);
    }//GEN-LAST:event_jaddpurchaseActionPerformed

    private void jaddusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddusersActionPerformed
        signup sgnup =new signup();
        sgnup.setVisible(true);
    }//GEN-LAST:event_jaddusersActionPerformed

    private void jpurchaselistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpurchaselistActionPerformed
       purchaselist prchselist =new purchaselist();
       prchselist.setVisible(true);
    }//GEN-LAST:event_jpurchaselistActionPerformed

    private void jsaleslistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsaleslistActionPerformed
        saleslist selllist =new saleslist();
        selllist.setVisible(true);
    }//GEN-LAST:event_jsaleslistActionPerformed

    private void jcustomerlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcustomerlistActionPerformed
       customerlist cslist =new customerlist();
       cslist.setVisible(true);
    }//GEN-LAST:event_jcustomerlistActionPerformed

    private void jcompanylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcompanylistActionPerformed
        comapnylist cslist =new comapnylist();
        cslist.setVisible(true);
    }//GEN-LAST:event_jcompanylistActionPerformed

    private void jaddinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddinvoiceActionPerformed
        sales sell =new sales();
        sell.setVisible(true);
    }//GEN-LAST:event_jaddinvoiceActionPerformed

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
       login lgn=new login();
       this.setVisible(false);
       lgn.setVisible(true);
       
    }//GEN-LAST:event_jlogoutActionPerformed

    private void jlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlogoutMouseClicked
        login lgn=new login();
       lgn.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jlogoutMouseClicked

    private void jlogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlogoutKeyPressed
       login lgn=new login();
       lgn.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jlogoutKeyPressed

    private void jcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jcloseMouseClicked

    private void jcloseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcloseKeyPressed
       System.exit(0);
    }//GEN-LAST:event_jcloseKeyPressed

                                   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jaddcompany;
    private javax.swing.JMenuItem jaddcustomer;
    private javax.swing.JMenuItem jaddinvoice;
    private javax.swing.JMenuItem jaddpurchase;
    private javax.swing.JMenuItem jaddusers;
    private javax.swing.JMenu jclose;
    private javax.swing.JMenu jcompany;
    private javax.swing.JMenuItem jcompanylist;
    private javax.swing.JMenu jcustomer;
    private javax.swing.JMenuItem jcustomerlist;
    public javax.swing.JLabel jlbl;
    public javax.swing.JLabel jlblname;
    private javax.swing.JLabel jlbltype;
    private javax.swing.JMenu jlist;
    private javax.swing.JMenu jlogout;
    private javax.swing.JMenu jpurchase;
    private javax.swing.JMenuItem jpurchaselist;
    private javax.swing.JMenu jsales;
    private javax.swing.JMenuItem jsaleslist;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JTable jtable;
    private javax.swing.JMenu jusers;
    // End of variables declaration//GEN-END:variables
}
